CURRENT_DIR = $(shell pwd)

.PHONY: all constant linear quadratic

all: constant linear quadratic

constant:
	cd $(CURRENT_DIR)/constant; make all

linear:
	cd $(CURRENT_DIR)/linear; make all

quadratic:
	cd $(CURRENT_DIR)/quadratic; make all
