cuIBM: Logger Class Reference
Logger Class Reference
Monitors the time spent to achieve a certain task.
#include <logger.h>
Public Member Functions
Logger ()
Constructor.
Logger (std::string folder)
Constructor overloading. Opens files given the case directory.
~Logger ()
Destructor.
void startTimer (std::string event)
Starts the timer.
void stopTimer (std::string event, bool print=false)
Stops the timer.
void eraseTimer (std::string event)
Erases the timer of a given event.
void resetTimer ()
Resets the timer.
void resetTimeStep ()
Resets the time-step timer.
void allocMemory (std::string event, double bytes)
Allocates memory for an event given a size.
void freeMemory (std::string event, double bytes)
Frees memory allocated for a given event.
void printTime (std::string event)
Prints the time spent to achieve a event.
void printMemory (std::string event)
Prints the memory allocated for a given event.
void printAllTime ()
Prints time spent for each event as well as the total time.
void writeLegend ()
Writes the events into a file.
void writeTime ()
Writes time spent for each event into a file.
void writeTimeStep (int n)
Writes time spent for an iteration into a file.
Public Attributes
bool printNow
boolean to print or not the time in the terminal
Private Member Functions
double get_time ()
Gets the time of the day.
Private Attributes
std::ofstream file
file to write the time spent
std::ofstream stepFile
file to write the time spent for 1 step
std::ofstream legendFile
file to write the name of the events
Event tic
contain the starting time of events
Event timer
contain the total time spent of events during the simulation
Event timeStep
contain the tiem spent times of events for 1 step
Event memory
contain info about the memomry allocated for events
Detailed Description
Monitors the time spent to achieve a certain task.
Definition at line 33 of file logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
Logger::Logger () inline
Constructor.
Definition at line 62 of file logger.h.
Logger() [2/2]
Logger::Logger (std::string folder) inline
Constructor overloading. Opens files given the case directory.
Parameters
folder directory of the simulation
Definition at line 69 of file logger.h.
~Logger()
Logger::~Logger () inline
Destructor.
Definition at line 80 of file logger.h.
References writeLegend().
Member Function Documentation
allocMemory()
void Logger::allocMemory (std::string event, double bytes) inline
Allocates memory for an event given a size.
Parameters
event a string that describes the event
bytes the number of bytes for allocation
Definition at line 146 of file logger.h.
eraseTimer()
void Logger::eraseTimer (std::string event) inline
Erases the timer of a given event.
Parameters
event a string that describes the event
Definition at line 117 of file logger.h.
freeMemory()
void Logger::freeMemory (std::string event, double bytes) inline
Frees memory allocated for a given event.
Parameters
event a string that describes the event
bytes the number of bytes
Definition at line 157 of file logger.h.
get_time()
double Logger::get_time () inline private
Gets the time of the day.
Returns
the time of the day (micro-second precision)
Definition at line 49 of file logger.h.
Referenced by startTimer(), and stopTimer().
printAllTime()
void Logger::printAllTime () inline
Prints time spent for each event as well as the total time.
Definition at line 185 of file logger.h.
Referenced by io::printTimingInfo().
printMemory()
void Logger::printMemory (std::string event) inline
Prints the memory allocated for a given event.
Parameters
event a string that describes the event
Definition at line 177 of file logger.h.
printTime()
void Logger::printTime (std::string event) inline
Prints the time spent to achieve a event.
Parameters
event a string that describes the event
Definition at line 167 of file logger.h.
resetTimer()
void Logger::resetTimer () inline
Resets the timer.
Definition at line 125 of file logger.h.
resetTimeStep()
void Logger::resetTimeStep () inline
Resets the time-step timer.
Definition at line 134 of file logger.h.
startTimer()
void Logger::startTimer (std::string event) inline
Starts the timer.
Parameters
event a string that describes the event to monitor
Definition at line 92 of file logger.h.
References get_time().
stopTimer()
void Logger::stopTimer (std::string event, bool print = false) inline
Stops the timer.
Parameters
event a string that describes the event monitored
print boolean to print the time or not in the terminal
Definition at line 103 of file logger.h.
References get_time().
writeLegend()
void Logger::writeLegend () inline
Writes the events into a file.
Definition at line 203 of file logger.h.
Referenced by ~Logger().
writeTime()
void Logger::writeTime () inline
Writes time spent for each event into a file.
Definition at line 214 of file logger.h.
writeTimeStep()
void Logger::writeTimeStep (int n) inline
Writes time spent for an iteration into a file.
Parameters
n the iteration number
Definition at line 225 of file logger.h.
Member Data Documentation
file
std::ofstream Logger::file private
file to write the time spent
Definition at line 36 of file logger.h.
legendFile
std::ofstream Logger::legendFile private
file to write the name of the events
Definition at line 36 of file logger.h.
memory
Event Logger::memory private
contain info about the memomry allocated for events
Definition at line 39 of file logger.h.
printNow
bool Logger::printNow
boolean to print or not the time in the terminal
Definition at line 57 of file logger.h.
stepFile
std::ofstream Logger::stepFile private
file to write the time spent for 1 step
Definition at line 36 of file logger.h.
tic
Event Logger::tic private
contain the starting time of events
Definition at line 39 of file logger.h.
timer
Event Logger::timer private
contain the total time spent of events during the simulation
Definition at line 39 of file logger.h.
timeStep
Event Logger::timeStep private
contain the tiem spent times of events for 1 step
Definition at line 39 of file logger.h.
The documentation for this class was generated from the following file:
/Users/mesnardo/git/barbagroup/cuIBM/src/utilities/logger.h