cuIBM: TairaColoniusSolver< memoryType > Class Template Reference
TairaColoniusSolver< memoryType > Class Template Reference
Solves the Navier-Stokes equations using the Immersed boundary method from Taira and Colonius (2007).
#include <TairaColoniusSolver.h>
Public Member Functions
TairaColoniusSolver (parameterDB *pDB=NULL, domain *dInfo=NULL)
Constructor. Copies the database and information about the computational grid.
virtual void initialise ()
Initializes the solvers.
virtual void writeData ()
Calculates and writes forces acting on each immersed body at current time.
virtual std::string name ()
Returns the name of the solver.
Public Member Functions inherited from NSWithBody< memoryType >
virtual void writeCommon ()
Writes flow variables and position of body points into files.
virtual void shutDown ()
Closes iteration file and force file.
Public Member Functions inherited from NavierStokesSolver< memoryType >
NavierStokesSolver (parameterDB *pDB=NULL, domain *dInfo=NULL)
Constructor. Copies the database and information about the computational grid.
void stepTime ()
Calculates the variables at the next time step.
bool finished ()
Evaluates the condition required to stop the simulation.
Private Member Functions
virtual void generateQT ()
void updateQT ()
virtual void generateBC2 ()
virtual void updateSolverState ()
Updates the location of the bodies and re-generates appropriate matrices.
virtual void calculateForce ()
Calculates forces acting on each immersed body.
template<>
void generateBC2 ()
Generates the right hand-side of the Poisson system (on the host).
template<>
void generateBC2 ()
Generates the right hand-side of the Poisson system (on the device).
template<>
void updateQT ()
Updates the interpolation matrix using the current locations of body points (on the host).
template<>
void updateQT ()
Updates the interpolation matrix using the current locations of body points (on the device).
template<>
void generateQT ()
Generates the transposed gradient matrix and interpolation matrix (on the host).
template<>
void generateQT ()
Generates the transposed gradient matrix and interpolation matrix (on the device).
Private Attributes
cusp::coo_matrix< int, real, memoryType > E
Interpolation matrix from the Eulerian grid to the Lagrangian points.
cusp::coo_matrix< int, real, memoryType > ET
Regularization matrix form the Lagrangian points to the Eulerian grid.
Additional Inherited Members
Protected Member Functions inherited from NSWithBody< memoryType >
void initialiseBodies ()
Stores the parameters of the simulation and initializes the location and motion of each immersed bodies.
void updateBodies ()
Updates location and motion of each immersed body at current time.
template<>
void calculateForce ()
Doing nothing (on the host).
template<>
void calculateForce ()
Calculates forces acting on an immersed body (on the device).
Protected Member Functions inherited from NavierStokesSolver< memoryType >
void initialiseCommon ()
Initializes parameters common to all Navier-Stokes solvers.
void initialiseArrays (int numQ, int numLambda)
Initializes all arrays required to solve the Navier-Stokes equations.
virtual void initialiseFluxes ()
virtual void initialiseFluxes (real *q)
Initializes velocity flux vectors.
void initialiseBoundaryArrays ()
Initializes boundary velocity arrays with values stored in the database.
void assembleMatrices ()
Assembles matrices of the intermediate flux solver and the Poisson solver.
void generateM ()
virtual void generateL ()
virtual void generateA (real alpha)
void generateBN ()
Generates approximate inverse of the matrix resulting from implicit velocity terms.
void updateQ (real gamma)
Doing nothing.
virtual void generateC ()
void generateRN ()
Generates explicit terms of the momentum equation.
void calculateExplicitQTerms ()
virtual void calculateExplicitLambdaTerms ()
Doing nothing. Used in methods that use the explicit pressure term in the intermediate velocity solve step, such as FadlunEtAlSolver and DFModifiedSolver.
virtual void generateBC1 ()
virtual void assembleRHS1 ()
Assembles the right hand-side of the system for the intermediate flux.
void assembleRHS2 ()
Assembles the right hand-side of the Poisson system.
virtual void solveIntermediateVelocity ()
Solves for the intermediate flux velocity.
virtual void solvePoisson ()
Solves the Poisson system.
virtual void projectionStep ()
Projects the flux onto the divergence-free field.
void updateBoundaryConditions ()
Doing nothing.
template<>
void generateA (real alpha)
Assembles the matrix from implicit terms of momentum equation (device).
template<>
void generateA (real alpha)
Assembles the matrix from implicit terms of momentum equation (host).
template<>
void generateBC1 ()
Generates inhomogeneous boundary conditions from the discrete Laplacian operator (device).
template<>
void generateBC1 ()
Generates inhomogeneous boundary conditions from the discrete Laplacian operator (host).
template<>
void generateBC2 ()
Generates inhomogeneous boundary conditions from the discrete continuity equation (host).
template<>
void generateBC2 ()
Generates inhomogeneous boundary conditions from the discrete continuity equation (device).
template<>
void generateL ()
Generates the discrete Laplacian matrix (on the host).
template<>
void generateL ()
Generates the discrete Laplacian matrix (on the device).
template<>
void generateM ()
Generates the mass matrix and its inverse (on the host).
template<>
void generateM ()
Generates the mass matrix and its inverse (on the device).
template<>
void generateQT ()
Generates the discrete divergence matrix (on the host).
template<>
void generateQT ()
Generates the discrete divergence matrix (on the device).
template<>
void calculateExplicitQTerms ()
Generates explicit terms that arise from the velocity fluxes (device).
template<>
void calculateExplicitQTerms ()
Generates explicit terms that arise from the velocity fluxes (host).
template<>
void initialiseFluxes ()
Initializes velocity flux vectors (on the host).
template<>
void initialiseFluxes ()
Initializes velocity flux vectors (on the device).
template<>
void generateC ()
Generates the matrix of the Poisson solver (on the device).
template<>
void generateC ()
Generates the matrix of the Poisson solver (on the host).
Protected Attributes inherited from NSWithBody< memoryType >
bodies< memoryType > B
bodies in the flow
real forceX
force acting on each body in the x-direction
real forceY
force acting on each body in the y-direction
std::ofstream forceFile
file to write the forces
Protected Attributes inherited from NavierStokesSolver< memoryType >
parameterDB * paramDB
database that contains all the simulation parameters
domain * domInfo
computational grid information
integrationScheme intgSchm
instance of the class integrationScheme
real QCoeff
cusp::coo_matrix< int, real, memoryType > M
diagonal mass matrix
cusp::coo_matrix< int, real, memoryType > Minv
inverse of the mass matrix
cusp::coo_matrix< int, real, memoryType > L
discrete Laplacian matrix
cusp::coo_matrix< int, real, memoryType > A
combination of mass and Laplacian matrices
cusp::coo_matrix< int, real, memoryType > Q
gradient matrix (and regularization matrix if immersed body)
cusp::coo_matrix< int, real, memoryType > QT
transposed gradient matrix (and interpolation matrix if immersed body)
cusp::coo_matrix< int, real, memoryType > BN
N-th order Taylor series expansion of the inverse of A.
cusp::coo_matrix< int, real, memoryType > C
matrix of the Poisson system
cusp::array1d< real, memoryType > q
velocity flux vector
cusp::array1d< real, memoryType > qStar
intermediate velocity flux vector
cusp::array1d< real, memoryType > qOld
velocity flux vector at the previous time-step
cusp::array1d< real, memoryType > lambda
pressure vector (and body forces if immersed body)
cusp::array1d< real, memoryType > rn
explicit terms of the momentum equation
cusp::array1d< real, memoryType > bc1
inhomogeneous boundary conditions from the discrete Laplacian operator
cusp::array1d< real, memoryType > bc2
inhomogeneous boundary conditions from the discrete continuity equation
cusp::array1d< real, memoryType > rhs1
right hand-side of the system for the intermediate velocity flux vector
cusp::array1d< real, memoryType > rhs2
right hand-side of the Poisson system
cusp::array1d< real, memoryType > H
hold convective terms from previous time step
cusp::array1d< real, memoryType > temp1
temporary 1D Cusp array
cusp::array1d< real, memoryType > temp2
temporary 1D Cusp array
cusp::array1d< real, memoryType > bc [4]
array that contains the boundary conditions of the rectangular domain
preconditioner< cusp::coo_matrix< int, real, memoryType > > * PC1
preconditioner for the intermediate flux solver
preconditioner< cusp::coo_matrix< int, real, memoryType > > * PC2
preconditioner for the Poisson solver
size_t timeStep
iteration number
size_t subStep
number of sub-iterations
size_t iterationCount1
number of iteration to solve the intermediate fluxes
size_t iterationCount2
number of iteration to solve the Poisson equation
Logger logger
instance of the class Logger to track time of different tasks
std::ofstream iterationsFile
file that contains the number of iterations
Detailed Description
template<typename memoryType>
class TairaColoniusSolver< memoryType >
Solves the Navier-Stokes equations using the Immersed boundary method from Taira and Colonius (2007).
The immersed boundary method: a projection approach
Taira K. and Colonius T.
Journal of Computational Physics
Volume 225 Number 2 (2007).
Definition at line 24 of file TairaColoniusSolver.h.
Constructor & Destructor Documentation
TairaColoniusSolver()
template<typename memoryType > TairaColoniusSolver< memoryType >::TairaColoniusSolver (parameterDB * pDB = NULL, domain * dInfo = NULL)
Constructor. Copies the database and information about the computational grid.
Definition at line 16 of file TairaColoniusSolver.cu.
Member Function Documentation
calculateForce()
template<typename memoryType > void TairaColoniusSolver< memoryType >::calculateForce () private virtual
Calculates forces acting on each immersed body.
For each immersed body, it spreads the Lagrangian forces on the Eulerian grid and sum the entire field to get the x- and y- components of the force.
Reimplemented from NSWithBody< memoryType >.
Definition at line 19 of file calculateForce.inl.
References NSWithBody< memoryType >::forceX, and NSWithBody< memoryType >::forceY.
generateBC2() [1/3]
template<> void TairaColoniusSolver< host_memory >::generateBC2 () private virtual
Generates the right hand-side of the Poisson system (on the host).
It contains the inhomogeneous boundary conditions from the discrete divergence operator, as well as the no-slip boundary condition at the body surface.
no-slip condition on the body surface
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 19 of file generateBC2.inl.
References XMINUS, XPLUS, YMINUS, and YPLUS.
generateBC2() [2/3]
template<typename memoryType> virtual void TairaColoniusSolver< memoryType >::generateBC2 () private virtual
Reimplemented from NavierStokesSolver< memoryType >.
generateBC2() [3/3]
template<> void TairaColoniusSolver< device_memory >::generateBC2 () private virtual
Generates the right hand-side of the Poisson system (on the device).
It contains the inhomogeneous boundary conditions from the discrete divergence operator, as well as the no-slip boundary condition at the body surface.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 70 of file generateBC2.inl.
References XMINUS, XPLUS, YMINUS, and YPLUS.
generateQT() [1/3]
template<typename memoryType> virtual void TairaColoniusSolver< memoryType >::generateQT () private virtual
Reimplemented from NavierStokesSolver< memoryType >.
generateQT() [2/3]
template<> void TairaColoniusSolver< host_memory >::generateQT () private virtual
Generates the transposed gradient matrix and interpolation matrix (on the host).
QT is an (np + 2*nb) x nuv matrix
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 119 of file generateQT.inl.
References kernels::generateQT(), and kernels::updateQT().
generateQT() [3/3]
template<> void TairaColoniusSolver< device_memory >::generateQT () private virtual
Generates the transposed gradient matrix and interpolation matrix (on the device).
QT is an (np + 2*nb) x nuv matrix
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 149 of file generateQT.inl.
References kernels::generateQT(), and kernels::updateQT().
initialise()
template<typename memoryType > void TairaColoniusSolver< memoryType >::initialise () virtual
Initializes the solvers.
Initializes bodies, arrays and matrices of the intermediate flux solver and the Poisson solver.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 31 of file TairaColoniusSolver.cu.
References NavierStokesSolver< memoryType >::assembleMatrices(), NavierStokesSolver< memoryType >::initialiseArrays(), NSWithBody< memoryType >::initialiseBodies(), and NavierStokesSolver< memoryType >::initialiseCommon().
name()
template<typename memoryType> virtual std::string TairaColoniusSolver< memoryType >::name () inline virtual
Returns the name of the solver.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 59 of file TairaColoniusSolver.h.
updateQT() [1/3]
template<> void TairaColoniusSolver< host_memory >::updateQT () private
Updates the interpolation matrix using the current locations of body points (on the host).
Typically called after the body has moved.
Definition at line 20 of file generateQT.inl.
References kernels::updateQTHost().
updateQT() [2/3]
template<typename memoryType> void TairaColoniusSolver< memoryType >::updateQT () private
updateQT() [3/3]
template<> void TairaColoniusSolver< device_memory >::updateQT () private
Updates the interpolation matrix using the current locations of body points (on the device).
Typically called after the body has moved.
Definition at line 69 of file generateQT.inl.
References BLOCKSIZE.
updateSolverState()
template<typename memoryType > void TairaColoniusSolver< memoryType >::updateSolverState () private virtual
Updates the location of the bodies and re-generates appropriate matrices.
Updates only done if the bodies are moving. It re-generates the interpolation matrix, therefore the Poisson matrix too.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 98 of file TairaColoniusSolver.cu.
References NavierStokesSolver< memoryType >::generateC(), NSWithBody< memoryType >::updateBodies(), and kernels::updateQT().
writeData()
template<typename memoryType > void TairaColoniusSolver< memoryType >::writeData () virtual
Calculates and writes forces acting on each immersed body at current time.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 61 of file TairaColoniusSolver.cu.
References NSWithBody< memoryType >::forceX, NSWithBody< memoryType >::forceY, and NSWithBody< memoryType >::writeCommon().
Member Data Documentation
E
template<typename memoryType> cusp::coo_matrix<int, real, memoryType> TairaColoniusSolver< memoryType >::E private
Interpolation matrix from the Eulerian grid to the Lagrangian points.
Definition at line 28 of file TairaColoniusSolver.h.
ET
template<typename memoryType> cusp::coo_matrix<int, real, memoryType> TairaColoniusSolver< memoryType >::ET private
Regularization matrix form the Lagrangian points to the Eulerian grid.
Definition at line 28 of file TairaColoniusSolver.h.
The documentation for this class was generated from the following files:
/Users/mesnardo/git/barbagroup/cuIBM/src/solvers/TairaColoniusSolver.h
/Users/mesnardo/git/barbagroup/cuIBM/src/solvers/TairaColonius/calculateForce.inl
/Users/mesnardo/git/barbagroup/cuIBM/src/solvers/TairaColoniusSolver.cu