cuIBM: NSWithBody< memoryType > Class Template Reference
NSWithBody< memoryType > Class Template Reference
Generic Navier-Stokes solver in the presence of immersed boundaries.
#include <NSWithBody.h>
Public Member Functions
virtual void writeCommon ()
Writes flow variables and position of body points into files.
virtual void shutDown ()
Closes iteration file and force file.
Public Member Functions inherited from NavierStokesSolver< memoryType >
NavierStokesSolver (parameterDB *pDB=NULL, domain *dInfo=NULL)
Constructor. Copies the database and information about the computational grid.
virtual void initialise ()
Initializes parameters, arrays and matrices required for the simulation.
void stepTime ()
Calculates the variables at the next time step.
virtual void writeData ()
Writes data into files.
bool finished ()
Evaluates the condition required to stop the simulation.
virtual std::string name ()
Returns the name of the current solver.
Protected Member Functions
virtual void calculateForce ()
void initialiseBodies ()
Stores the parameters of the simulation and initializes the location and motion of each immersed bodies.
void updateBodies ()
Updates location and motion of each immersed body at current time.
template<>
void calculateForce ()
Calculates forces acting on an immersed body.
Protected Member Functions inherited from NavierStokesSolver< memoryType >
void initialiseCommon ()
Initializes parameters common to all Navier-Stokes solvers.
void initialiseArrays (int numQ, int numLambda)
Initializes all arrays required to solve the Navier-Stokes equations.
virtual void initialiseFluxes ()
virtual void initialiseFluxes (real *q)
Initializes velocity flux vectors.
void initialiseBoundaryArrays ()
Initializes boundary velocity arrays with values stored in the database.
void assembleMatrices ()
Assembles matrices of the intermediate flux solver and the Poisson solver.
void generateM ()
virtual void generateL ()
virtual void generateA (real alpha)
void generateBN ()
Generates approximate inverse of the matrix resulting from implicit velocity terms.
virtual void generateQT ()
void updateQ (real gamma)
Doing nothing.
virtual void generateC ()
void generateRN ()
Generates explicit terms of the momentum equation.
void calculateExplicitQTerms ()
virtual void calculateExplicitLambdaTerms ()
Doing nothing. Used in methods that use the explicit pressure term in the intermediate velocity solve step, such as FadlunEtAlSolver and DFModifiedSolver.
virtual void generateBC1 ()
virtual void generateBC2 ()
virtual void assembleRHS1 ()
Assembles the right hand-side of the system for the intermediate flux.
void assembleRHS2 ()
Assembles the right hand-side of the Poisson system.
virtual void solveIntermediateVelocity ()
Solves for the intermediate flux velocity.
virtual void solvePoisson ()
Solves the Poisson system.
virtual void projectionStep ()
Projects the flux onto the divergence-free field.
void updateBoundaryConditions ()
Doing nothing.
virtual void updateSolverState ()
Doing nothing. Used in immersed boundary methods when the body moves.
template<>
void generateA (real alpha)
Assembles the matrix from implicit terms of momentum equation.
template<>
void generateBC1 ()
Generates inhomogeneous boundary conditions from the discrete Laplacian operator.
template<>
void generateBC2 ()
Generates inhomogeneous boundary conditions from the discrete continuity equation.
template<>
void generateL ()
Generates the discrete Laplacian matrix.
template<>
void generateM ()
Generates the mass matrix and its inverse.
template<>
void generateQT ()
Generates the discrete divergence matrix.
template<>
void calculateExplicitQTerms ()
Generates explicit terms that arise from the velocity fluxes.
template<>
void initialiseFluxes ()
Initializes velocity flux vectors (on the device).
template<>
void generateC ()
Generates the matrix of the Poisson solver.
Protected Attributes
bodies< memoryType > B
bodies in the flow
real forceX
force acting on each body in the x-direction
real forceY
force acting on each body in the y-direction
std::ofstream forceFile
file to write the forces
Protected Attributes inherited from NavierStokesSolver< memoryType >
parameterDB * paramDB
database that contains all the simulation parameters
domain * domInfo
computational grid information
integrationScheme intgSchm
instance of the class integrationScheme
real QCoeff
cusp::coo_matrix< int, real, memoryType > M
diagonal mass matrix
cusp::coo_matrix< int, real, memoryType > Minv
inverse of the mass matrix
cusp::coo_matrix< int, real, memoryType > L
discrete Laplacian matrix
cusp::coo_matrix< int, real, memoryType > A
combination of mass and Laplacian matrices
cusp::coo_matrix< int, real, memoryType > Q
gradient matrix (and regularization matrix if immersed body)
cusp::coo_matrix< int, real, memoryType > QT
transposed gradient matrix (and interpolation matrix if immersed body)
cusp::coo_matrix< int, real, memoryType > BN
N-th order Taylor series expansion of the inverse of A.
cusp::coo_matrix< int, real, memoryType > C
matrix of the Poisson system
cusp::array1d< real, memoryType > q
velocity flux vector
cusp::array1d< real, memoryType > qStar
intermediate velocity flux vector
cusp::array1d< real, memoryType > qOld
velocity flux vector at the previous time-step
cusp::array1d< real, memoryType > lambda
pressure vector (and body forces if immersed body)
cusp::array1d< real, memoryType > rn
explicit terms of the momentum equation
cusp::array1d< real, memoryType > bc1
inhomogeneous boundary conditions from the discrete Laplacian operator
cusp::array1d< real, memoryType > bc2
inhomogeneous boundary conditions from the discrete continuity equation
cusp::array1d< real, memoryType > rhs1
right hand-side of the system for the intermediate velocity flux vector
cusp::array1d< real, memoryType > rhs2
right hand-side of the Poisson system
cusp::array1d< real, memoryType > H
hold convective terms from previous time step
cusp::array1d< real, memoryType > temp1
temporary 1D Cusp array
cusp::array1d< real, memoryType > temp2
temporary 1D Cusp array
cusp::array1d< real, memoryType > bc [4]
array that contains the boundary conditions of the rectangular domain
preconditioner< cusp::coo_matrix< int, real, memoryType > > * PC1
preconditioner for the intermediate flux solver
preconditioner< cusp::coo_matrix< int, real, memoryType > > * PC2
preconditioner for the Poisson solver
size_t timeStep
iteration number
size_t subStep
number of sub-iterations
size_t iterationCount1
number of iteration to solve the intermediate fluxes
size_t iterationCount2
number of iteration to solve the Poisson equation
Logger logger
instance of the class Logger to track time of different tasks
std::ofstream iterationsFile
file that contains the number of iterations
Detailed Description
template<typename memoryType>
class NSWithBody< memoryType >
Generic Navier-Stokes solver in the presence of immersed boundaries.
The class inherits from the class NavierStokesSolver.
Definition at line 21 of file NSWithBody.h.
Member Function Documentation
template<typename memoryType> virtual void NSWithBody< memoryType >::calculateForce () protected virtual
Reimplemented in TairaColoniusSolver< memoryType >.
Referenced by DirectForcingSolver< memoryType >::writeData().
template<> void NSWithBody< device_memory >::calculateForce () protected
Calculates forces acting on an immersed body.
Uses the control volume approach explained by Lai and Peskin (2000). This is a general method that can be used with any immersed boundary method. It uses only the velocity and pressure fields to calculate the forces, and does not involve any body forces on the immersed boundary. Currently works only for one body.
Definition at line 68 of file NSWithBody.cu.
References kernels::forceX(), and kernels::forceY().
template<typename memoryType > void NSWithBody< memoryType >::initialiseBodies () protected
Stores the parameters of the simulation and initializes the location and motion of each immersed bodies.
Definition at line 16 of file NSWithBody.cu.
References NavierStokesSolver< memoryType >::initialise().
Referenced by TairaColoniusSolver< memoryType >::initialise(), and DirectForcingSolver< memoryType >::initialise().
template<typename memoryType > void NSWithBody< memoryType >::shutDown () virtual
Closes iteration file and force file.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 159 of file NSWithBody.cu.
References io::printTimingInfo().
template<typename memoryType > void NSWithBody< memoryType >::updateBodies () protected
Updates location and motion of each immersed body at current time.
Definition at line 45 of file NSWithBody.cu.
Referenced by TairaColoniusSolver< memoryType >::updateSolverState(), and DirectForcingSolver< memoryType >::updateSolverState().
template<typename memoryType > void NSWithBody< memoryType >::writeCommon () virtual
Writes flow variables and position of body points into files.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 136 of file NSWithBody.cu.
References NavierStokesSolver< memoryType >::writeCommon().
Referenced by TairaColoniusSolver< memoryType >::writeData(), and DirectForcingSolver< memoryType >::writeData().
Member Data Documentation
template<typename memoryType> bodies<memoryType> NSWithBody< memoryType >::B protected
bodies in the flow
Definition at line 24 of file NSWithBody.h.
template<typename memoryType> std::ofstream NSWithBody< memoryType >::forceFile protected
file to write the forces
Definition at line 29 of file NSWithBody.h.
template<typename memoryType> real NSWithBody< memoryType >::forceX protected
force acting on each body in the x-direction
Definition at line 26 of file NSWithBody.h.
Referenced by TairaColoniusSolver< memoryType >::calculateForce(), and TairaColoniusSolver< memoryType >::writeData().
template<typename memoryType> real NSWithBody< memoryType >::forceY protected
force acting on each body in the y-direction
Definition at line 26 of file NSWithBody.h.
Referenced by TairaColoniusSolver< memoryType >::calculateForce(), and TairaColoniusSolver< memoryType >::writeData().
The documentation for this class was generated from the following files:
/home/mesnardo/git/barbagroup/cuIBM/src/solvers/NSWithBody.h
/home/mesnardo/git/barbagroup/cuIBM/src/solvers/NSWithBody.cu