cuIBM: DirectForcingSolver< memoryType > Class Template Reference
DirectForcingSolver< memoryType > Class Template Reference
A fully discrete formulation of the direct forcing method.
#include <DirectForcingSolver.h>
Public Member Functions
DirectForcingSolver (parameterDB *pDB=NULL, domain *dInfo=NULL)
Constructor. Initializes the simulation parameters and the domain info.
virtual void initialise ()
Initialize the vectors used in the simulation.
virtual void writeData ()
Writes the velocity, pressure, force and mass flux data at every save point.
virtual std::string name ()
Returns the name of the solver as a string.
Public Member Functions inherited from NSWithBody< memoryType >
virtual void writeCommon ()
Writes flow variables and position of body points into files.
virtual void shutDown ()
Closes iteration file and force file.
Public Member Functions inherited from NavierStokesSolver< memoryType >
NavierStokesSolver (parameterDB *pDB=NULL, domain *dInfo=NULL)
Constructor. Copies the database and information about the computational grid.
void stepTime ()
Calculates the variables at the next time step.
bool finished ()
Evaluates the condition required to stop the simulation.
Protected Member Functions
void tagPoints ()
void tagPoints (real *bx, real *by, real *uB, real *vB)
Tags all the forcing nodes required for the type of linear interpolation explained in the paper by Fadlun et al. (2000).
virtual void generateA (real alpha)
virtual void generateL ()
void generateQT (int *QTRows, int *QTCols, real *QTVals)
virtual void generateQT ()
Compute the divergence operator (transpose of the gradient one).
void updateQ ()
virtual void generateC ()
Generates the right-hand side matrix in the Poisson step.
virtual void assembleRHS1 ()
Assembles the matrix rhs1 for DirectForcingSolver.
void updateRHS1 ()
virtual void updateSolverState ()
Updates the matrices every time the body is moved.
virtual void projectionStep ()
Projects the pressure gradient on to the intermediate velocity field to obtain the divergence-free velocity field at the next time step.
void writeMassFluxInfo ()
Prints the min, max and sum of the divergences of the velocity field in every cell of the domain.
template<>
void generateA (real alpha)
Generates the matrix A on the device.
template<>
void generateA (real alpha)
Generates the matrix A on the host.
template<>
void generateL ()
Sets up the Laplacian matrix for the implicit diffusion term. Uses second order central differences on the non-uniform grid.
template<>
void generateL ()
Sets up the Laplacian matrix for the implicit diffusion term. Uses second order central differences on the non-uniform grid.
template<>
void updateQ ()
Update the gradient operator.
template<>
void updateQ ()
Update the gradient operator (device).
template<>
void tagPoints ()
Tags the forcing nodes among the velocity nodes, i.e. the nodes at which the velocity interpolation is performed.
template<>
void tagPoints ()
Tags the forcing nodes among the velocity nodes, i.e. the nodes at which the velocity interpolation is performed.
template<>
void updateRHS1 ()
Update the RHS of the velocity system (device).
template<>
void updateRHS1 ()
Update the RHS of the velocity system (host).
Protected Member Functions inherited from NSWithBody< memoryType >
virtual void calculateForce ()
void initialiseBodies ()
Stores the parameters of the simulation and initializes the location and motion of each immersed bodies.
void updateBodies ()
Updates location and motion of each immersed body at current time.
template<>
void calculateForce ()
Doing nothing (on the host).
template<>
void calculateForce ()
Calculates forces acting on an immersed body (on the device).
Protected Member Functions inherited from NavierStokesSolver< memoryType >
void initialiseCommon ()
Initializes parameters common to all Navier-Stokes solvers.
void initialiseArrays (int numQ, int numLambda)
Initializes all arrays required to solve the Navier-Stokes equations.
virtual void initialiseFluxes ()
virtual void initialiseFluxes (real *q)
Initializes velocity flux vectors.
void initialiseBoundaryArrays ()
Initializes boundary velocity arrays with values stored in the database.
void assembleMatrices ()
Assembles matrices of the intermediate flux solver and the Poisson solver.
void generateM ()
void generateBN ()
Generates approximate inverse of the matrix resulting from implicit velocity terms.
void updateQ (real gamma)
Doing nothing.
void generateRN ()
Generates explicit terms of the momentum equation.
void calculateExplicitQTerms ()
virtual void calculateExplicitLambdaTerms ()
Doing nothing. Used in methods that use the explicit pressure term in the intermediate velocity solve step, such as FadlunEtAlSolver and DFModifiedSolver.
virtual void generateBC1 ()
virtual void generateBC2 ()
void assembleRHS2 ()
Assembles the right hand-side of the Poisson system.
virtual void solveIntermediateVelocity ()
Solves for the intermediate flux velocity.
virtual void solvePoisson ()
Solves the Poisson system.
void updateBoundaryConditions ()
Doing nothing.
template<>
void generateA (real alpha)
Assembles the matrix from implicit terms of momentum equation (device).
template<>
void generateA (real alpha)
Assembles the matrix from implicit terms of momentum equation (host).
template<>
void generateBC1 ()
Generates inhomogeneous boundary conditions from the discrete Laplacian operator (device).
template<>
void generateBC1 ()
Generates inhomogeneous boundary conditions from the discrete Laplacian operator (host).
template<>
void generateBC2 ()
Generates inhomogeneous boundary conditions from the discrete continuity equation (host).
template<>
void generateBC2 ()
Generates inhomogeneous boundary conditions from the discrete continuity equation (device).
template<>
void generateL ()
Generates the discrete Laplacian matrix (on the host).
template<>
void generateL ()
Generates the discrete Laplacian matrix (on the device).
template<>
void generateM ()
Generates the mass matrix and its inverse (on the host).
template<>
void generateM ()
Generates the mass matrix and its inverse (on the device).
template<>
void generateQT ()
Generates the discrete divergence matrix (on the host).
template<>
void generateQT ()
Generates the discrete divergence matrix (on the device).
template<>
void calculateExplicitQTerms ()
Generates explicit terms that arise from the velocity fluxes (device).
template<>
void calculateExplicitQTerms ()
Generates explicit terms that arise from the velocity fluxes (host).
template<>
void initialiseFluxes ()
Initializes velocity flux vectors (on the host).
template<>
void initialiseFluxes ()
Initializes velocity flux vectors (on the device).
template<>
void generateC ()
Generates the matrix of the Poisson solver (on the device).
template<>
void generateC ()
Generates the matrix of the Poisson solver (on the host).
Protected Attributes
cusp::array1d< int, host_memory > tags
vector used to differentiate forcing points from regular ones (host)
cusp::array1d< int, host_memory > tags2
vector used to differentiate forcing points from regular ones (host)
cusp::array1d< int, device_memory > tagsD
vector used to differentiate forcing points from regular ones (device)
cusp::array1d< int, device_memory > tags2D
vector used to differentiate forcing points from regular ones (device)
vecH coeffs
coefficients of interpolation (host)
vecH coeffs2
other coefficients of interpolation; quadratic interpolation (host)
vecD coeffsD
coefficients of interpolation (device)
vecD coeffs2D
other coefficients of interpolation; quadratic interpolation (device)
vecH uv
velocity field (host)
vecD uvD
velocity field (device)
cusp::array1d< real, memoryType > pressure
pressure field
Protected Attributes inherited from NSWithBody< memoryType >
bodies< memoryType > B
bodies in the flow
real forceX
force acting on each body in the x-direction
real forceY
force acting on each body in the y-direction
std::ofstream forceFile
file to write the forces
Protected Attributes inherited from NavierStokesSolver< memoryType >
parameterDB * paramDB
database that contains all the simulation parameters
domain * domInfo
computational grid information
integrationScheme intgSchm
instance of the class integrationScheme
real QCoeff
cusp::coo_matrix< int, real, memoryType > M
diagonal mass matrix
cusp::coo_matrix< int, real, memoryType > Minv
inverse of the mass matrix
cusp::coo_matrix< int, real, memoryType > L
discrete Laplacian matrix
cusp::coo_matrix< int, real, memoryType > A
combination of mass and Laplacian matrices
cusp::coo_matrix< int, real, memoryType > Q
gradient matrix (and regularization matrix if immersed body)
cusp::coo_matrix< int, real, memoryType > QT
transposed gradient matrix (and interpolation matrix if immersed body)
cusp::coo_matrix< int, real, memoryType > BN
N-th order Taylor series expansion of the inverse of A.
cusp::coo_matrix< int, real, memoryType > C
matrix of the Poisson system
cusp::array1d< real, memoryType > q
velocity flux vector
cusp::array1d< real, memoryType > qStar
intermediate velocity flux vector
cusp::array1d< real, memoryType > qOld
velocity flux vector at the previous time-step
cusp::array1d< real, memoryType > lambda
pressure vector (and body forces if immersed body)
cusp::array1d< real, memoryType > rn
explicit terms of the momentum equation
cusp::array1d< real, memoryType > bc1
inhomogeneous boundary conditions from the discrete Laplacian operator
cusp::array1d< real, memoryType > bc2
inhomogeneous boundary conditions from the discrete continuity equation
cusp::array1d< real, memoryType > rhs1
right hand-side of the system for the intermediate velocity flux vector
cusp::array1d< real, memoryType > rhs2
right hand-side of the Poisson system
cusp::array1d< real, memoryType > H
hold convective terms from previous time step
cusp::array1d< real, memoryType > temp1
temporary 1D Cusp array
cusp::array1d< real, memoryType > temp2
temporary 1D Cusp array
cusp::array1d< real, memoryType > bc [4]
array that contains the boundary conditions of the rectangular domain
preconditioner< cusp::coo_matrix< int, real, memoryType > > * PC1
preconditioner for the intermediate flux solver
preconditioner< cusp::coo_matrix< int, real, memoryType > > * PC2
preconditioner for the Poisson solver
size_t timeStep
iteration number
size_t subStep
number of sub-iterations
size_t iterationCount1
number of iteration to solve the intermediate fluxes
size_t iterationCount2
number of iteration to solve the Poisson equation
Logger logger
instance of the class Logger to track time of different tasks
std::ofstream iterationsFile
file that contains the number of iterations
Detailed Description
template<typename memoryType>
class DirectForcingSolver< memoryType >
A fully discrete formulation of the direct forcing method.
Based on the method first proposed by Fadlun et al (2000) with modifications by Kim et al (2001). It does not follow the same equations that they used, but use a fractional step method starting with the discretized equations, based on the idea by Perot (1993).
This method does not use an explicit pressure term in the step where the intermediate velocity is calculated, and the pressure is directly obtained from the Poisson equation.
Definition at line 27 of file DirectForcingSolver.h.
Constructor & Destructor Documentation
DirectForcingSolver()
template<typename memoryType > DirectForcingSolver< memoryType >::DirectForcingSolver (parameterDB * pDB = NULL, domain * dInfo = NULL)
Constructor. Initializes the simulation parameters and the domain info.
Definition at line 18 of file DirectForcingSolver.cu.
Referenced by DirectForcingSolver< memoryType >::generateQT().
Member Function Documentation
assembleRHS1()
template<typename memoryType > void DirectForcingSolver< memoryType >::assembleRHS1 () protected virtual
Assembles the matrix rhs1 for DirectForcingSolver.
This function first calls the function assembleRHS1 from NavierStokesSolver. Then it called the function updateRHS1 to modify only the elements of the vector that correspond to the interpolation nodes.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 99 of file DirectForcingSolver.cu.
References NavierStokesSolver< memoryType >::assembleRHS1(), and kernels::updateRHS1().
Referenced by DirectForcingSolver< memoryType >::generateQT().
generateA() [1/3]
template<> void DirectForcingSolver< device_memory >::generateA (real alpha) protected virtual
Generates the matrix A on the device.
Parameters
alpha Coefficient of the implicit part of the diffusion term. 1 for backward Euler, 0.5 for Crank-Nicolson and 0 for explicit Euler.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 18 of file generateA.inl.
generateA() [2/3]
template<typename memoryType> virtual void DirectForcingSolver< memoryType >::generateA (real alpha) protected virtual
Reimplemented from NavierStokesSolver< memoryType >.
generateA() [3/3]
template<> void DirectForcingSolver< host_memory >::generateA (real alpha) protected virtual
Generates the matrix A on the host.
Parameters
alpha Coefficient of the implicit part of the diffusion term. 1 for backward Euler, 0.5 for Crank-Nicolson and 0 for explicit Euler.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 54 of file generateA.inl.
generateC()
template<typename memoryType > void DirectForcingSolver< memoryType >::generateC () protected virtual
Generates the right-hand side matrix in the Poisson step.
Because the fully discrete direct forcing method separates the domains inside and outside the immersed boundary, and Neumann boundary conditions are enforced at the immersed boundary, a point also needs to be fixed inside the immersed boundary, so that Poisson system does not have any zero eigenvalues.
In this function, phi at a point that corresponds to the center of the grid is fixed as zero. This is the cell with indices (nx/2, ny/2), and is the center in terms of the indices and not the physical location in space. Of course, this is invalid if the interior of the body does not include this point, and the solution obtained will be unphysical.
This needs to be done in a better way (i.e. by locating points that are inside the immersed boundaries, and fixing them to zero)
Reimplemented from NavierStokesSolver< memoryType >.
Reimplemented in FEAModifiedSolver< memoryType >, and FadlunEtAlSolver< memoryType >.
Definition at line 206 of file DirectForcingSolver.cu.
References NavierStokesSolver< memoryType >::generateC().
Referenced by DirectForcingSolver< memoryType >::generateQT().
generateL() [1/3]
template<> void DirectForcingSolver< host_memory >::generateL () protected virtual
Sets up the Laplacian matrix for the implicit diffusion term. Uses second order central differences on the non-uniform grid.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 13 of file generateL.inl.
generateL() [2/3]
template<> void DirectForcingSolver< device_memory >::generateL () protected virtual
Sets up the Laplacian matrix for the implicit diffusion term. Uses second order central differences on the non-uniform grid.
DO NOT FORGET (IMPLEMENTED) A is generated as M-alpha*LHost But some values of L are the interpolation values of the direct forcing method These should not be multplied by alpha
The sign of the interpolation coeffs is the opposite of that in the toy python code since A is obtained by subtracting alpha*L from M
(NOT IMPLEMENTED YET) Also remember to take alpha into account in BC1 for moving bodies
x-component
y-component
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 23 of file generateL.inl.
References LINEAR, and QUADRATIC.
generateL() [3/3]
template<typename memoryType> virtual void DirectForcingSolver< memoryType >::generateL () protected virtual
Reimplemented from NavierStokesSolver< memoryType >.
generateQT() [1/2]
template<typename memoryType> void DirectForcingSolver< memoryType >::generateQT (int * QTRows, int * QTCols, real * QTVals) inline protected
Definition at line 57 of file DirectForcingSolver.h.
References DirectForcingSolver< memoryType >::assembleRHS1(), DirectForcingSolver< memoryType >::DirectForcingSolver(), DirectForcingSolver< memoryType >::generateC(), DirectForcingSolver< memoryType >::generateQT(), DirectForcingSolver< memoryType >::initialise(), DirectForcingSolver< memoryType >::projectionStep(), DirectForcingSolver< memoryType >::updateQ(), DirectForcingSolver< memoryType >::updateRHS1(), DirectForcingSolver< memoryType >::updateSolverState(), DirectForcingSolver< memoryType >::writeData(), and DirectForcingSolver< memoryType >::writeMassFluxInfo().
generateQT() [2/2]
template<typename memoryType > void DirectForcingSolver< memoryType >::generateQT () protected virtual
Compute the divergence operator (transpose of the gradient one).
Reimplemented from NavierStokesSolver< memoryType >.
Reimplemented in FEAModifiedSolver< memoryType >, FadlunEtAlSolver< memoryType >, and DFImprovedSolver< memoryType >.
Definition at line 55 of file generateQT.inl.
References NavierStokesSolver< memoryType >::generateQT(), and kernels::updateQ().
Referenced by DirectForcingSolver< memoryType >::generateQT().
initialise()
template<typename memoryType > void DirectForcingSolver< memoryType >::initialise () virtual
Initialize the vectors used in the simulation.
Reimplemented from NavierStokesSolver< memoryType >.
Reimplemented in DiffusionSolver< memoryType >.
Definition at line 29 of file DirectForcingSolver.cu.
References NavierStokesSolver< memoryType >::assembleMatrices(), NavierStokesSolver< memoryType >::initialiseArrays(), NSWithBody< memoryType >::initialiseBodies(), and NavierStokesSolver< memoryType >::initialiseCommon().
Referenced by DirectForcingSolver< memoryType >::generateQT(), and DiffusionSolver< memoryType >::initialise().
name()
template<typename memoryType> virtual std::string DirectForcingSolver< memoryType >::name () inline virtual
Returns the name of the solver as a string.
Reimplemented from NavierStokesSolver< memoryType >.
Reimplemented in FEAModifiedSolver< memoryType >, FadlunEtAlSolver< memoryType >, DiffusionSolver< memoryType >, DFModifiedSolver< memoryType >, and DFImprovedSolver< memoryType >.
Definition at line 93 of file DirectForcingSolver.h.
projectionStep()
template<typename memoryType > void DirectForcingSolver< memoryType >::projectionStep () protected virtual
Projects the pressure gradient on to the intermediate velocity field to obtain the divergence-free velocity field at the next time step.
Reimplemented from NavierStokesSolver< memoryType >.
Reimplemented in DFModifiedSolver< memoryType >, and DiffusionSolver< memoryType >.
Definition at line 153 of file DirectForcingSolver.cu.
References NavierStokesSolver< memoryType >::projectionStep().
Referenced by DirectForcingSolver< memoryType >::generateQT().
tagPoints() [1/4]
template<> void DirectForcingSolver< host_memory >::tagPoints () protected
Tags the forcing nodes among the velocity nodes, i.e. the nodes at which the velocity interpolation is performed.
Definition at line 13 of file tagPoints.inl.
tagPoints() [2/4]
template<> void DirectForcingSolver< device_memory >::tagPoints () protected
Tags the forcing nodes among the velocity nodes, i.e. the nodes at which the velocity interpolation is performed.
Definition at line 33 of file tagPoints.inl.
tagPoints() [3/4]
template<typename memoryType> void DirectForcingSolver< memoryType >::tagPoints () protected
tagPoints() [4/4]
template<typename memoryType > void DirectForcingSolver< memoryType >::tagPoints (real * bx, real * by, real * uB, real * vB) protected
Tags all the forcing nodes required for the type of linear interpolation explained in the paper by Fadlun et al. (2000).
It uses a raytracing algorithm to detect points that are near the boundary, and just outside it. For more information about the algorithm, read the section on ray-crossings in the Search and Intersection chapter of the book Computational Geometry in C by Joseph O'Rourke.
Parameters
bx host array of the x-coordinates of the boundary points
by host array of the y-coordinates of the boundary points
uB host array of the x-components of the boundary velocities
vB host array of the y-components of the boundary velocities
if the ray intersects the boundary segment top endpoint must be strictly above the ray bottom can be on or below the ray
Definition at line 80 of file tagPoints.inl.
References CONSTANT, LINEAR, and QUADRATIC.
updateQ() [1/3]
template<> void DirectForcingSolver< host_memory >::updateQ () protected
Update the gradient operator.
Definition at line 15 of file generateQT.inl.
updateQ() [2/3]
template<> void DirectForcingSolver< device_memory >::updateQ () protected
Update the gradient operator (device).
After the Q matrix has been set up for the entire grid, this function removes the non-zeros that correspond to the velocity nodes where the interpolation is performed, i.e. it sets the fluxes there to zero. This routine is specific to DirectForcingSolver.
Definition at line 29 of file generateQT.inl.
updateQ() [3/3]
template<typename memoryType> void DirectForcingSolver< memoryType >::updateQ () protected
Referenced by DFImprovedSolver< memoryType >::generateQT(), and DirectForcingSolver< memoryType >::generateQT().
updateRHS1() [1/3]
template<> void DirectForcingSolver< device_memory >::updateRHS1 () protected
Update the RHS of the velocity system (device).
The vector rhs1 is first set up as if it would have been in the absence of an immersed boundary. This function then changes values in the vector that correspond to the forcing nodes on the grid, replacing them with the rhs values from the interpolation relations.
Definition at line 20 of file updateRHS1.inl.
updateRHS1() [2/3]
template<> void DirectForcingSolver< host_memory >::updateRHS1 () protected
Update the RHS of the velocity system (host).
The vector rhs1 is first set up as if it would have been in the absence of an immersed boundary. This function then changes values in the vector that correspond to the forcing nodes on the grid, replacing them with the rhs values from the interpolation relations.
Definition at line 61 of file updateRHS1.inl.
updateRHS1() [3/3]
template<typename memoryType> void DirectForcingSolver< memoryType >::updateRHS1 () protected
Referenced by DirectForcingSolver< memoryType >::generateQT().
updateSolverState()
template<typename memoryType > void DirectForcingSolver< memoryType >::updateSolverState () protected virtual
Updates the matrices every time the body is moved.
Change the location of the body points, re-tags all the points on the velocity grid to locate the new forcing nodes. Reassembles the matrices. Moving bodies have not been tested for DirectForcingSolver.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 75 of file DirectForcingSolver.cu.
References NavierStokesSolver< memoryType >::assembleMatrices(), and NSWithBody< memoryType >::updateBodies().
Referenced by DirectForcingSolver< memoryType >::generateQT().
writeData()
template<typename memoryType > void DirectForcingSolver< memoryType >::writeData () virtual
Writes the velocity, pressure, force and mass flux data at every save point.
Reimplemented from NavierStokesSolver< memoryType >.
Definition at line 167 of file DirectForcingSolver.cu.
References NSWithBody< memoryType >::calculateForce(), kernels::forceX(), and NSWithBody< memoryType >::writeCommon().
Referenced by DirectForcingSolver< memoryType >::generateQT().
writeMassFluxInfo()
template<typename memoryType > void DirectForcingSolver< memoryType >::writeMassFluxInfo () protected
Prints the min, max and sum of the divergences of the velocity field in every cell of the domain.
The divergence is calculated as QT*q, which is technically the sum of the mass fluxes in every cell. This QT is also differs depending on the Direct Forcing method used.
Definition at line 118 of file DirectForcingSolver.cu.
Referenced by DirectForcingSolver< memoryType >::generateQT().
Member Data Documentation
coeffs
template<typename memoryType> vecH DirectForcingSolver< memoryType >::coeffs protected
coefficients of interpolation (host)
Definition at line 37 of file DirectForcingSolver.h.
coeffs2
template<typename memoryType> vecH DirectForcingSolver< memoryType >::coeffs2 protected
other coefficients of interpolation; quadratic interpolation (host)
Definition at line 37 of file DirectForcingSolver.h.
coeffs2D
template<typename memoryType> vecD DirectForcingSolver< memoryType >::coeffs2D protected
other coefficients of interpolation; quadratic interpolation (device)
Definition at line 39 of file DirectForcingSolver.h.
coeffsD
template<typename memoryType> vecD DirectForcingSolver< memoryType >::coeffsD protected
coefficients of interpolation (device)
Definition at line 39 of file DirectForcingSolver.h.
pressure
template<typename memoryType> cusp::array1d<real, memoryType> DirectForcingSolver< memoryType >::pressure protected
pressure field
Definition at line 44 of file DirectForcingSolver.h.
tags
template<typename memoryType> cusp::array1d<int, host_memory> DirectForcingSolver< memoryType >::tags protected
vector used to differentiate forcing points from regular ones (host)
Definition at line 32 of file DirectForcingSolver.h.
tags2
template<typename memoryType> cusp::array1d<int, host_memory> DirectForcingSolver< memoryType >::tags2 protected
vector used to differentiate forcing points from regular ones (host)
Definition at line 32 of file DirectForcingSolver.h.
tags2D
template<typename memoryType> cusp::array1d<int, device_memory> DirectForcingSolver< memoryType >::tags2D protected
vector used to differentiate forcing points from regular ones (device)
Definition at line 35 of file DirectForcingSolver.h.
tagsD
template<typename memoryType> cusp::array1d<int, device_memory> DirectForcingSolver< memoryType >::tagsD protected
vector used to differentiate forcing points from regular ones (device)
Definition at line 35 of file DirectForcingSolver.h.
uv
template<typename memoryType> vecH DirectForcingSolver< memoryType >::uv protected
velocity field (host)
Definition at line 42 of file DirectForcingSolver.h.
uvD
template<typename memoryType> vecD DirectForcingSolver< memoryType >::uvD protected
velocity field (device)
Definition at line 43 of file DirectForcingSolver.h.
The documentation for this class was generated from the following files:
/Users/mesnardo/git/barbagroup/cuIBM/src/solvers/DirectForcingSolver.h
/Users/mesnardo/git/barbagroup/cuIBM/src/solvers/DirectForcing/generateQT.inl
/Users/mesnardo/git/barbagroup/cuIBM/src/solvers/DirectForcing/tagPoints.inl
/Users/mesnardo/git/barbagroup/cuIBM/src/solvers/DirectForcingSolver.cu