cuIBM: property Class Reference
property Class Reference
Stores information about a property in a generic way.
#include <parameterDB.h>
Public Member Functions
property ()
Constructor. Initializes the memory to zero.
template<typename T >
T get ()
Gets the value of the property as a given type.
template<typename T >
void set (T v)
Sets the value of the property given a type.
const char * print ()
Returns a string describing the value of property as appropriate.
template<>
std::string get ()
Gets the value of the property as a string.
template<>
void set (std::string s)
Sets the value of the property given a string.
Private Member Functions
template<typename T >
T getInternal ()
Private Attributes
const std::type_info * type
char value [256]
Detailed Description
Stores information about a property in a generic way.
Definition at line 23 of file parameterDB.h.
Constructor & Destructor Documentation
property()
property::property () inline
Constructor. Initializes the memory to zero.
Definition at line 37 of file parameterDB.h.
References print().
Member Function Documentation
get() [1/2]
template<typename T > T property::get ()
Gets the value of the property as a given type.
Returns
the value of the property as a given type
Definition at line 70 of file parameterDB.cu.
References value.
get() [2/2]
template<> template boundaryCondition ** property::get< boundaryCondition **> ()
Gets the value of the property as a string.
Returns
the value of the property as a string
Definition at line 58 of file parameterDB.cu.
References value.
getInternal()
template<typename T > T property::getInternal () private
print()
const char * property::print ()
Returns a string describing the value of property as appropriate.
Returns
a constant character pointer
Definition at line 96 of file parameterDB.cu.
References toString(), type, and value.
Referenced by property().
set() [1/2]
template<typename T > void property::set (T v)
Sets the value of the property given a type.
Parameters
v the value
Definition at line 132 of file parameterDB.cu.
References type, and value.
set() [2/2]
template<> void property::set (std::string s)
Sets the value of the property given a string.
Parameters
s a string
Definition at line 120 of file parameterDB.cu.
References value.
Member Data Documentation
type
const std::type_info* property::type private
Definition at line 28 of file parameterDB.h.
Referenced by print(), and set().
value
char property::value[256] private
Definition at line 31 of file parameterDB.h.
Referenced by get(), print(), and set().
The documentation for this class was generated from the following files:
/Users/mesnardo/git/barbagroup/cuIBM/src/utilities/parameterDB.h
/Users/mesnardo/git/barbagroup/cuIBM/src/utilities/parameterDB.cu