cuIBM: /Users/mesnardo/git/barbagroup/cuIBM/src/solvers/createSolver.h File Reference
createSolver.h File Reference
Declaration of the function that creates the Navier-Stokes solver.
#include "NavierStokesSolver.h"
#include "DirectForcingSolver.h"
#include "FadlunEtAlSolver.h"
#include "TairaColoniusSolver.h"
#include "DiffusionSolver.h"
#include "DFModifiedSolver.h"
#include "DFImprovedSolver.h"
Functions
template<typename memoryType >
NavierStokesSolver< memoryType > * createSolver (parameterDB &paramDB, domain &domInfo)
Creates the appropriate Navier-Stokes solver.
Detailed Description
Declaration of the function that creates the Navier-Stokes solver.
Definition in file createSolver.h.
Function Documentation
createSolver()
template<typename memoryType > NavierStokesSolver<memoryType>* createSolver (parameterDB & paramDB, domain & domInfo)
Creates the appropriate Navier-Stokes solver.
The type of solver depends on the IBM used. If there is no immersed body in the flow, an instance of the class NavierStokesSolver is created. If TAIRA_COLONIUS is the IBM used, an instance of the class TairaColoniusSolver is created, that inherits from the class NavierStokesSolver.
Parameters
paramDB database that contains all the simulation parameters
domInfo information about the computational grid
Returns
an instance of the appropriate class
Definition at line 26 of file createSolver.cu.
References createSolver(), DF_IMPROVED, DF_MODIFIED, DIFFUSION, DIRECT_FORCING, FADLUN_ET_AL, FEA_MODIFIED, DFImprovedSolver< memoryType >::name(), NAVIER_STOKES, SAIKI_BIRINGEN, and TAIRA_COLONIUS.
Referenced by createSolver().