cuIBM: /home/mesnardo/git/barbagroup/cuIBM/src/cuIBM.cu File Reference
cuIBM.cu File Reference
Main source file of cuIBM.
#include "utilities/types.h"
#include "utilities/helpers.h"
#include "utilities/domain.h"
#include "io/io.h"
#include "solvers/createSolver.h"
Functions
int main (int argc, char **argv)
Main function.
Detailed Description
Main source file of cuIBM.
Definition in file cuIBM.cu.
Function Documentation
int main (int argc, char ** argv)
Main function.
Definition at line 17 of file cuIBM.cu.
References NavierStokesSolver< memoryType >::finished(), NavierStokesSolver< memoryType >::initialise(), io::printDeviceMemoryUsage(), io::printSimulationInfo(), io::readInputs(), NavierStokesSolver< memoryType >::shutDown(), NavierStokesSolver< memoryType >::stepTime(), and NavierStokesSolver< memoryType >::writeData().