cuIBM: /Users/mesnardo/git/barbagroup/cuIBM/src/solvers/kernels/generateE.cu File Reference
generateE.cu File Reference
Implementation of the kernels to generate elements of the interpolation matrix.
#include "generateE.h"
Namespaces
kernels
Contains all the custom-written CUDA kernels.
Functions
__device__ real dhRomaDeviceE (real x, real h)
Discrete delta function defined by Roma et al. (1999).
__device__ real deltaDeviceE (real x, real y, real h)
Two-dimension discrete delta function.
void kernels::generateEHost (int *ERows, int *ECols, real *EVals, int nx, int ny, real *x, real *y, real *dx, int totalPoints, real *xB, real *yB, int *I, int *J)
Generates the interpolation matrix (on the host).
__global__ void kernels::generateE (int *ERows, int *ECols, real *EVals, int nx, int ny, real *x, real *y, real *dx, int totalPoints, real *xB, real *yB, int *I, int *J)
Computes elements of the interpolation matrix.
Detailed Description
Implementation of the kernels to generate elements of the interpolation matrix.
Definition in file generateE.cu.
Function Documentation
deltaDeviceE()
__device__ real deltaDeviceE (real x, real y, real h)
Two-dimension discrete delta function.
Parameters
x x-component of the vector defined between two points
y y-component of the vector defined between two points
h the grid-spacing
Returns
the value of the discrete delta function in 2D
Definition at line 42 of file generateE.cu.
References dhRomaDeviceE().
Referenced by kernels::generateE().
dhRomaDeviceE()
__device__ real dhRomaDeviceE (real x, real h)
Discrete delta function defined by Roma et al. (1999).
Parameters
x x- or y- component of the vector defined between two points
h the grid-spacing
Returns
the value of the discrete delta function
Definition at line 19 of file generateE.cu.
Referenced by deltaDeviceE().