cuIBM: /Users/mesnardo/git/barbagroup/cuIBM/src/solvers/kernels/generateQT.cu File Reference
generateQT.cu File Reference
Implementation of the kernels to generate the gradient matrix and interpolation matrix.
#include "generateQT.h"
Namespaces
kernels
Contains all the custom-written CUDA kernels.
Functions
__device__ real dhRomaDeviceQT (real x, real h)
Discrete delta function defined by Roma et al. (1999).
__device__ real deltaDeviceQT (real x, real y, real h)
Two-dimensional discrete delta function.
__global__ void kernels::updateQ (int *QRows, int *QCols, real *QVals, int QSize, int *tags)
Update the gradient operator at forcing nodes.
__global__ void kernels::updateQT (int *QTRows, int *QTCols, real *QTVals, int QTSize, int *tags, real *coeffs)
Update the divergence operator at forcing nodes.
void kernels::generateQT (int *QTRows, int *QTCols, real *QTVals, int nx, int ny)
Generates the divergence matrix (on the host).
__global__ void kernels::updateQT (int *QTRows, int *QTCols, real *QTVals, int *ERows, int *ECols, real *EVals, int nx, int ny, real *x, real *y, real *dx, int totalPoints, real *xB, real *yB, int *I, int *J)
Updates elements of the divergence matrix and the interpolation matrix.
void kernels::updateQTHost (int *QTRows, int *QTCols, real *QTVals, int *ERows, int *ECols, real *EVals, int nx, int ny, real *x, real *y, real *dx, int totalPoints, real *xB, real *yB, int *I, int *J)
Updates the divergence matrix and the interpolation matrix (on the host).
Detailed Description
Implementation of the kernels to generate the gradient matrix and interpolation matrix.
Definition in file generateQT.cu.
Function Documentation
deltaDeviceQT()
__device__ real deltaDeviceQT (real x, real y, real h)
Two-dimensional discrete delta function.
Parameters
x x-component of the vector defined between two points
y y-component of the vector defined between two points
h the grid-spacing
Returns
the value of the discrete delta function in 2D
Definition at line 42 of file generateQT.cu.
References dhRomaDeviceQT().
Referenced by kernels::updateQT().
dhRomaDeviceQT()
__device__ real dhRomaDeviceQT (real x, real h)
Discrete delta function defined by Roma et al. (1999).
Parameters
x x- or y- component of the vector defined between two points
h the grid-spacing
Returns
the value of the discrete delta function
Definition at line 19 of file generateQT.cu.
Referenced by deltaDeviceQT().