cuIBM: /Users/mesnardo/git/barbagroup/cuIBM/src/utilities/helpers.h File Reference
helpers.h File Reference
Declaration of the discrete delta function.
#include "types.h"
Functions
real dhRoma (real x, real h)
Discrete delta function from Roma et al. (1999).
real delta (real x, real y, real h)
Two-dimensional discrete delta function.
Detailed Description
Declaration of the discrete delta function.
Definition in file helpers.h.
Function Documentation
delta()
real delta (real x, real y, real h)
Two-dimensional discrete delta function.
Parameters
x x-coordinate of the grid point
y y-coordinate of the grid point
h grid-spacing in the uniform region
Returns
the value of the discrete Delta function in 2D
Definition at line 44 of file helpers.cu.
References dhRoma().
Referenced by kernels::generateEHost(), and kernels::updateQTHost().
dhRoma()
real dhRoma (real x, real h)
Discrete delta function from Roma et al. (1999).
A.M. Roma, C.S. Peskin, M.J. Berger. An adaptative version of the immersed boundary method. J. Comput. Phys. 153, 509-534 (1999).
Parameters
x coordinate of the grid point
h grid-spacing in the uniform region
Returns
the value of the discrete delta function
Definition at line 22 of file helpers.cu.
Referenced by delta().