include Makefile.inc

#test:
#	echo $(PROJ_ROOT)
#	echo $(dir $(lastword $(MAKEFILE_LIST)))

# just so that make is not confused if there exist
# files called cuibm or clean
.PHONY: cuibm src/solvers/libsolvers.a clean

# this is the command called when 'make' is run in the command line
main: cuibm

# libraries generated by compiling the code
LIBS = lib/libNavierStokesSolvers.a lib/libCuspWrapped.a lib/libIO.a

# library generate by compiling the YAML headers
EXT_LIBS = external/lib/libyaml-cpp.a

# final library
FINAL_LIB = lib/libcuIBM.a

# everything after the colon is a prerequisite
# they are all targets that are executed in order before the current target
# if the targets are not explicitly defined, implicit rules are used
# targets are the usually the names of the files generated

# the implicit rule .cu.o converts src/parameterDB.cu to src/parameterDB.o

# link all the object files and libraries to create the executable bin/cuIBM
cuibm: src/parameterDB.o $(LIBS) $(EXT_LIBS)  src/cuIBM.o src/bodies.o 
	nvcc $? -o bin/cuIBM

#lib/libcuIBM.a: $(LIBS) $(EXT_LIBS)
#	cd lib; libtool -static -o libcuIBM.a $?

#  force_look is a dependency
#  it is always true. So this command is always executed
lib/libNavierStokesSolvers.a: force_look
	cd src/solvers; $(MAKE) $(MFLAGS)

lib/libCuspWrapped.a: force_look
	cd src/cusp/; $(MAKE) $(MFLAGS)
  
lib/libIO.a: force_look
	cd src/io/; $(MAKE) $(MFLAGS)

external/lib/libyaml-cpp.a:
	cd external; $(MAKE) $(MFLAGS) all

#  deletes all the object files
#  it seems MFLAGS hasn't been defined anywhere. The defaults are probably used.
#  @ at the beginning of a line suppresses output. This works only in Makefiles.
#  1. delete all the .a and .o files
#  2. cd to the concerned folders
#  3. run 'make clean' as defined in the Makefiles in those folders
clean:
	@rm -f lib/*.a bin/cuIBM src/*.o
	cd src/solvers; $(MAKE) $(MFLAGS) clean
	cd src/cusp; $(MAKE) $(MFLAGS) clean
	cd src/io; $(MAKE) $(MFLAGS) clean
	cd external; $(MAKE) $(MFLAGS) clean

#
force_look:
	true

#
.PHONY: cuibm

LidDrivenCavityRe100:
	bin/cuIBM -flowFile flows/cavity0100.yaml -domainFile domains/cavity0100.yaml -bodyFile bodies/empty.yaml -simulationFile simParams/cavity0100.yaml -folderName LidDrivenCavityRe100

LidDrivenCavityRe1000:
	bin/cuIBM -flowFile flows/cavity1000.yaml -domainFile domains/cavity1000.yaml -bodyFile bodies/empty.yaml -simulationFile simParams/cavity1000.yaml -folderName LidDrivenCavityRe1000

cylinderRe40: force_look
	bin/cuIBM -flowFile flows/openFlow0040.yaml -domainFile domains/openFlow0.025.yaml -bodyFile bodies/cylinder126.yaml -simulationFile simParams/cylinder0040.yaml -folderName cylinderRe40

cylinderRe550: force_look
	bin/cuIBM -flowFile flows/openFlow0550.yaml -domainFile domains/openFlow0.010.yaml -bodyFile bodies/cylinder315.yaml -simulationFile simParams/cylinder0550.yaml -folderName cylinderRe550

cylinderRe3000: force_look
	bin/cuIBM -flowFile flows/openFlow3000.yaml -domainFile domains/openFlow0.004.yaml -bodyFile bodies/cylinder786.yaml -simulationFile simParams/cylinder3000.yaml -folderName cylinderRe3000
