.PHONY: all

CUIBM=$(CUIBM_DIR)/bin/cuibm

all:
	$(CUIBM) -directory 25  > 25/run.log 2>&1
	$(CUIBM) -directory 75  > 75/run.log 2>&1
	$(CUIBM) -directory 225 > 225/run.log 2>&1
	$(CUIBM) -directory 675 > 675/run.log 2>&1
