.PHONY: all

CURRENT_DIR=$(shell pwd)

all:
	cd $(CURRENT_DIR)/circ_T00.25_20_0.00050; make all
	cd $(CURRENT_DIR)/circ_T00.25_25_0.00050; make all
	cd $(CURRENT_DIR)/circ_T00.25_30_0.00050; make all
	cd $(CURRENT_DIR)/uquad_T00.25_20_0.00050; make all
	cd $(CURRENT_DIR)/vquad_T00.25_20_0.00050; make all
