.PHONY: all

CUIBM=$(CUIBM_DIR)/bin/cuibm

all:
	$(CUIBM) -directory 30  > 30/run.log 2>&1
	$(CUIBM) -directory 90  > 90/run.log 2>&1
	$(CUIBM) -directory 270 > 270/run.log 2>&1
	$(CUIBM) -directory 810 > 810/run.log 2>&1
