.PHONY: all

CUIBM=$(CUIBM_DIR)/bin/cuibm

all:
	$(CUIBM) -directory 20  > 20/run.log 2>&1
	$(CUIBM) -directory 60  > 60/run.log 2>&1
	$(CUIBM) -directory 180 > 180/run.log 2>&1
	$(CUIBM) -directory 540 > 540/run.log 2>&1
